### ISSUE TITLE
A button or a link?

### ISSUE THREAD

**Issue by suustenvoorde** [DaanKorver/chippr-beyco-newspage#11]
https://kittygiraudel.com/2020/01/17/accessible-links-and-buttons-with-react/

https://github.com/DaanKorver/chippr-beyco-newspage/blob/a92d3cbfa3d27fca3239f8a35598cb52452d7fe0/src/components/Article.js#L23

**Comment by DaanKorver** [comment]
https://github.com/DaanKorver/chippr-beyco-newspage/blob/a92d3cbfa3d27fca3239f8a35598cb52452d7fe0/src/components/Article.js#L23

Button :+1:
